// eslint flat config — scoped to the dashboard SPA (crates/amux-dashboard/static).
//
// Purpose: the no-silent-actions static gate. Two silent-dead-handler bugs
// shipped in one week (schedule delete, then worker delete 2026-08-09) — both
// were an undefined name inside an async handler, so the rejection vanished and
// the UI did nothing. `no-undef` catches that class at lint time; the runtime
// unhandledrejection toast in app.js is the floor, this gate is the ceiling.
//
// Only high-signal correctness rules — this is a gate, not a style linter.
// Run it via: scripts/spa-lint.sh (regenerates the globals allowlist first).
import fs from 'node:fs';
import globals from 'globals';

// Generated by scripts/gen-spa-globals.mjs from the actual code (top-level
// declarations in static/*.js + index.html inline scripts + window.X= exports).
// The SPA is classic-script: hundreds of top-level names are its cross-script
// API surface, so they are globals by construction, not by hand-listing.
let generated = {};
try {
  generated = JSON.parse(fs.readFileSync(
    new URL('./crates/amux-dashboard/eslint.globals.generated.json', import.meta.url), 'utf8'));
} catch (e) {
  // spa-lint.sh always regenerates before linting; a direct `eslint` run
  // without the file should fail loudly on no-undef rather than silently
  // passing, so an empty fallback is correct here.
}

// Vendor globals from the CDN <script src=> tags in index.html — hand-listed
// because they are not in our source; each entry names its tag.
const vendorGlobals = {
  Papa: 'readonly',          // papaparse
  marked: 'readonly',        // marked
  DOMPurify: 'readonly',     // dompurify
  Sortable: 'readonly',      // sortablejs
  Quill: 'readonly',         // quill
  QuillMarkdown: 'readonly', // quilljs-markdown
  Chart: 'readonly',         // chart.js
  Motion: 'readonly',        // motion.dev
  GridStack: 'readonly',     // gridstack
  Terminal: 'readonly',      // @xterm/xterm
  FitAddon: 'readonly',      // @xterm/addon-fit
  WebLinksAddon: 'readonly', // @xterm/addon-web-links
  hljs: 'readonly',          // highlight.js
  L: 'readonly',             // leaflet (+ markercluster)
  FullCalendar: 'readonly',  // fullcalendar
  posthog: 'readonly',       // posthog snippet (index.html inline bootstrap)
};

const gateRules = {
  // THE rule this gate exists for: an undefined name in a handler dies as an
  // invisible rejected promise (worker-delete bug, 2026-08-09).
  'no-undef': 'error',
  // vars:'local' — top-level functions are the HTML onclick API surface, they
  // are legitimately "unused" inside app.js itself. caughtErrors:'none' —
  // `catch(e) {}` with unused e is the file's idiom for optional paths.
  'no-unused-vars': ['warn', { vars: 'local', args: 'after-used', caughtErrors: 'none' }],
  'no-dupe-keys': 'error',
  'no-unreachable': 'error',
  // checkLoops:false — while(true) polling loops are intentional in an SPA.
  'no-constant-condition': ['error', { checkLoops: false }],
};

export default [
  {
    // Page scripts: app.js and any future classic-script split.
    files: ['crates/amux-dashboard/static/*.js'],
    ignores: ['crates/amux-dashboard/static/sw.js'],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'script',
      globals: { ...globals.browser, ...vendorGlobals, ...generated },
    },
    rules: gateRules,
  },
  {
    // Service worker: worker scope, not page scope.
    files: ['crates/amux-dashboard/static/sw.js'],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'script',
      globals: { ...globals.serviceworker },
    },
    rules: gateRules,
  },
];
