#!/bin/bash
# Install the repo's git hooks (secret scan + Python/JS syntax checks).
# Run once after cloning:  ./scripts/install-hooks.sh
#
# THIS INSTALLS ONE FILE, and that is deliberate. The cross-session staged-guard
# (.git/hooks/amux-staged-guard) is NOT installed here: it is a generated
# artifact that amux-server.py writes per work_dir from _AMUX_GUARD_BODY, and it
# injects its own shim into whatever pre-commit exists. Installing a tracked copy
# from here made this script a second producer of a generated file, so running it
# overwrote the server's live guard with a frozen one — which reverted AC-241's
# improvement and would revert every later one. Fix the generator, never the
# generated file. If the guard is missing, start the amux server for that
# work_dir.
set -e
ROOT="$(git rev-parse --show-toplevel)"

install -m 0755 "$ROOT/scripts/git-hooks/pre-commit" "$ROOT/.git/hooks/pre-commit"

# Verify rather than announce (ethos #7): compare what landed against its source,
# so a stale installed copy cannot hide behind a success message. That drift was
# real and security-relevant — the AC-239 secret patterns (Clerk, R2, Slack,
# GitLab) sat in the tracked hook while .git/hooks/pre-commit was months old, so
# commits printed "Security scan passed" from a scanner that could match none of
# them.
if cmp -s "$ROOT/scripts/git-hooks/pre-commit" "$ROOT/.git/hooks/pre-commit"; then
  echo "  ok   .git/hooks/pre-commit matches scripts/git-hooks/pre-commit"
else
  echo "  FAIL .git/hooks/pre-commit differs from scripts/git-hooks/pre-commit" >&2
  exit 1
fi

# The staged-guard is the server's to install; report whether it is actually
# there instead of leaving its absence to be discovered by a sweep.
if [ -x "$ROOT/.git/hooks/amux-staged-guard" ]; then
  echo "  ok   .git/hooks/amux-staged-guard present (installed by amux-server.py)"
else
  echo "  note .git/hooks/amux-staged-guard absent — cross-session sweep protection is OFF."
  echo "       It is generated by amux-server.py; start the server for this work_dir." >&2
fi
echo "hooks installed: secret scan + Python/JS syntax."
